"""Python tools for checkers board states, rules, and validation."""

from .bitboard import (
    BLACK_PROMO_MASK,
    DARKS_MASK,
    WHITE_PROMO_MASK,
    apply_move,
    apply_turn,
    bitboards_from_ascii,
    bits_from_grid,
    capture_chains,
    draw_board,
    generate_move_templates,
    grid_from_bits,
    initial_position,
    is_dark,
    legal_moves,
    legal_turns,
    show_board,
    square_from_mask,
    square_mask,
    validate_position,
)
from .display import show_move_rows, show_primitive_rule_rows, show_state, show_turn, show_turn_rows
from .rules import (
    applicable_primitive_rules,
    apply_primitive_rule,
    legal_successors,
    move_record,
    moves_df,
    primitive_move_catalog_df,
    primitive_move_record,
    primitive_move_records,
    primitive_rule_applies,
    primitive_rule_catalog_df,
    primitive_rule_move,
    primitive_rule_promotes,
    primitive_rule_record,
    primitive_rule_records,
    primitive_rule_requires_king,
    primitive_rule_runtime_catalog_df,
    primitive_rule_runtime_record,
    primitive_rule_runtime_records,
    primitive_rule_state,
    state_record,
    turns_df,
)
from .state import BoardState, as_state

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "BLACK_PROMO_MASK",
    "BoardState",
    "DARKS_MASK",
    "WHITE_PROMO_MASK",
    "apply_move",
    "apply_primitive_rule",
    "apply_turn",
    "applicable_primitive_rules",
    "as_state",
    "bitboards_from_ascii",
    "bits_from_grid",
    "capture_chains",
    "draw_board",
    "generate_move_templates",
    "grid_from_bits",
    "initial_position",
    "is_dark",
    "legal_moves",
    "legal_successors",
    "legal_turns",
    "move_record",
    "moves_df",
    "primitive_move_catalog_df",
    "primitive_move_record",
    "primitive_move_records",
    "primitive_rule_applies",
    "primitive_rule_catalog_df",
    "primitive_rule_move",
    "primitive_rule_promotes",
    "primitive_rule_record",
    "primitive_rule_records",
    "primitive_rule_requires_king",
    "primitive_rule_runtime_catalog_df",
    "primitive_rule_runtime_record",
    "primitive_rule_runtime_records",
    "primitive_rule_state",
    "show_board",
    "show_move_rows",
    "show_primitive_rule_rows",
    "show_state",
    "show_turn",
    "show_turn_rows",
    "square_from_mask",
    "square_mask",
    "state_record",
    "turns_df",
    "validate_position",
]
