"""Python tools for checkers move generation and quiet-position tablebases."""

from .bitboard import (
    BLACK_PROMO_MASK,
    DARKS_MASK,
    WHITE_PROMO_MASK,
    apply_move,
    apply_turn,
    bitboards_from_ascii,
    bits_from_grid,
    capture_chains,
    expand_quiet_man_states,
    explore_quiet_man_positions,
    generate_move_templates,
    grid_from_bits,
    initial_position,
    is_dark,
    is_quiet_man_state,
    legal_moves,
    legal_turns,
    show_board,
    square_mask,
    validate_position,
)
from .quiet import (
    FORCED_CAPTURE,
    FORCED_CAPTURE_PROMOTION,
    PROMOTION,
    QUIET,
    TRANSITION_METADATA_KEYS,
    QuietPositionGraph,
    decode_state_key,
    encode_state,
    inspect_game_state,
    mask32_to64,
    mask64_to32,
    normalize_state_key,
    pack_state32,
    run_quiet_graph,
    split_state_key,
    square32_to64,
    square64_to32,
    state_key_record,
)

QuietTablebase = QuietPositionGraph

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "BLACK_PROMO_MASK",
    "DARKS_MASK",
    "FORCED_CAPTURE",
    "FORCED_CAPTURE_PROMOTION",
    "PROMOTION",
    "QUIET",
    "TRANSITION_METADATA_KEYS",
    "WHITE_PROMO_MASK",
    "QuietPositionGraph",
    "QuietTablebase",
    "apply_move",
    "apply_turn",
    "bitboards_from_ascii",
    "bits_from_grid",
    "capture_chains",
    "decode_state_key",
    "encode_state",
    "expand_quiet_man_states",
    "explore_quiet_man_positions",
    "generate_move_templates",
    "grid_from_bits",
    "initial_position",
    "inspect_game_state",
    "is_dark",
    "is_quiet_man_state",
    "legal_moves",
    "legal_turns",
    "mask32_to64",
    "mask64_to32",
    "normalize_state_key",
    "pack_state32",
    "run_quiet_graph",
    "show_board",
    "split_state_key",
    "square32_to64",
    "square64_to32",
    "square_mask",
    "state_key_record",
    "validate_position",
]
